// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$7 from "./loaders/actions/cart/addCoupon.ts";
import * as $$$8 from "./loaders/actions/cart/addItem.ts";
import * as $$$9 from "./loaders/actions/cart/removeCoupon.ts";
import * as $$$10 from "./loaders/actions/cart/removeItem.ts";
import * as $$$11 from "./loaders/avaliabilitySubscription.ts";
import * as $$$12 from "./loaders/cart.ts";
import * as $$$13 from "./loaders/config.ts";
import * as $$$14 from "./loaders/cookieNames.ts";
import * as $$$15 from "./loaders/handlers/proxy.ts";
import * as $$$0 from "./loaders/Layouts/Benefits.tsx";
import * as $$$1 from "./loaders/Layouts/Colors.tsx";
import * as $$$2 from "./loaders/Layouts/Filter.tsx";
import * as $$$3 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$4 from "./loaders/Layouts/Size.tsx";
import * as $$$5 from "./loaders/Layouts/SizeGuide.tsx";
import * as $$$6 from "./loaders/List/Sections.tsx";
import * as $$$16 from "./loaders/newsletter.ts";
import * as $$$17 from "./loaders/product/productDetails.ts";
import * as $$$18 from "./loaders/product/productList.ts";
import * as $$$19 from "./loaders/product/productListingPage.ts";
import * as $$$20 from "./loaders/product/productSearchPage.ts";
import * as $$$21 from "./loaders/proxy.ts";
import * as $$$22 from "./loaders/shippingSimulation.ts";
import * as $$$23 from "./loaders/suggestions.ts";
import * as $$$24 from "./loaders/url.ts";
import * as $$$25 from "./loaders/userInfo.ts";
import * as $$$$$$0 from "./sections/About/InfoCard.tsx";
import * as $$$$$$1 from "./sections/About/ProductCharacteristics.tsx";
import * as $$$$$$2 from "./sections/Animation/Animation.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$5 from "./sections/Content/Benefits.tsx";
import * as $$$$$$6 from "./sections/Content/ExternalContent.tsx";
import * as $$$$$$7 from "./sections/Content/Faq.tsx";
import * as $$$$$$8 from "./sections/Content/Logos.tsx";
import * as $$$$$$9 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$10 from "./sections/Footer/Footer.tsx";
import * as $$$$$$11 from "./sections/Gallery.tsx";
import * as $$$$$$12 from "./sections/Header/Header.tsx";
import * as $$$$$$13 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$14 from "./sections/Images/Carousel.tsx";
import * as $$$$$$15 from "./sections/Images/FeatureBlogArticle.tsx";
import * as $$$$$$16 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$17 from "./sections/Instagram/Instagram.tsx";
import * as $$$$$$18 from "./sections/Layout/Container.tsx";
import * as $$$$$$19 from "./sections/Layout/Flex.tsx";
import * as $$$$$$20 from "./sections/Layout/Grid.tsx";
import * as $$$$$$21 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$22 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$23 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$24 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$25 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$26 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$27 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$28 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$29 from "./sections/Product/NotFound.tsx";
import * as $$$$$$30 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$31 from "./sections/Product/ProductBenefits.tsx";
import * as $$$$$$32 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$33 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$34 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$35 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$36 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$37 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$38 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$39 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/persono/loaders/actions/cart/addCoupon.ts": $$$7,
    "deco-sites/persono/loaders/actions/cart/addItem.ts": $$$8,
    "deco-sites/persono/loaders/actions/cart/removeCoupon.ts": $$$9,
    "deco-sites/persono/loaders/actions/cart/removeItem.ts": $$$10,
    "deco-sites/persono/loaders/avaliabilitySubscription.ts": $$$11,
    "deco-sites/persono/loaders/cart.ts": $$$12,
    "deco-sites/persono/loaders/config.ts": $$$13,
    "deco-sites/persono/loaders/cookieNames.ts": $$$14,
    "deco-sites/persono/loaders/handlers/proxy.ts": $$$15,
    "deco-sites/persono/loaders/Layouts/Benefits.tsx": $$$0,
    "deco-sites/persono/loaders/Layouts/Colors.tsx": $$$1,
    "deco-sites/persono/loaders/Layouts/Filter.tsx": $$$2,
    "deco-sites/persono/loaders/Layouts/ProductCard.tsx": $$$3,
    "deco-sites/persono/loaders/Layouts/Size.tsx": $$$4,
    "deco-sites/persono/loaders/Layouts/SizeGuide.tsx": $$$5,
    "deco-sites/persono/loaders/List/Sections.tsx": $$$6,
    "deco-sites/persono/loaders/newsletter.ts": $$$16,
    "deco-sites/persono/loaders/product/productDetails.ts": $$$17,
    "deco-sites/persono/loaders/product/productList.ts": $$$18,
    "deco-sites/persono/loaders/product/productListingPage.ts": $$$19,
    "deco-sites/persono/loaders/product/productSearchPage.ts": $$$20,
    "deco-sites/persono/loaders/proxy.ts": $$$21,
    "deco-sites/persono/loaders/shippingSimulation.ts": $$$22,
    "deco-sites/persono/loaders/suggestions.ts": $$$23,
    "deco-sites/persono/loaders/url.ts": $$$24,
    "deco-sites/persono/loaders/userInfo.ts": $$$25,
  },
  "sections": {
    "deco-sites/persono/sections/About/InfoCard.tsx": $$$$$$0,
    "deco-sites/persono/sections/About/ProductCharacteristics.tsx": $$$$$$1,
    "deco-sites/persono/sections/Animation/Animation.tsx": $$$$$$2,
    "deco-sites/persono/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "deco-sites/persono/sections/Category/CategoryList.tsx": $$$$$$4,
    "deco-sites/persono/sections/Content/Benefits.tsx": $$$$$$5,
    "deco-sites/persono/sections/Content/ExternalContent.tsx": $$$$$$6,
    "deco-sites/persono/sections/Content/Faq.tsx": $$$$$$7,
    "deco-sites/persono/sections/Content/Logos.tsx": $$$$$$8,
    "deco-sites/persono/sections/Content/Testimonials.tsx": $$$$$$9,
    "deco-sites/persono/sections/Footer/Footer.tsx": $$$$$$10,
    "deco-sites/persono/sections/Gallery.tsx": $$$$$$11,
    "deco-sites/persono/sections/Header/Header.tsx": $$$$$$12,
    "deco-sites/persono/sections/Images/BannerGrid.tsx": $$$$$$13,
    "deco-sites/persono/sections/Images/Carousel.tsx": $$$$$$14,
    "deco-sites/persono/sections/Images/FeatureBlogArticle.tsx": $$$$$$15,
    "deco-sites/persono/sections/Images/ImageGallery.tsx": $$$$$$16,
    "deco-sites/persono/sections/Instagram/Instagram.tsx": $$$$$$17,
    "deco-sites/persono/sections/Layout/Container.tsx": $$$$$$18,
    "deco-sites/persono/sections/Layout/Flex.tsx": $$$$$$19,
    "deco-sites/persono/sections/Layout/Grid.tsx": $$$$$$20,
    "deco-sites/persono/sections/Layout/GridItem.tsx": $$$$$$21,
    "deco-sites/persono/sections/Links/LinkTree.tsx": $$$$$$22,
    "deco-sites/persono/sections/Links/Shortcuts.tsx": $$$$$$23,
    "deco-sites/persono/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$24,
    "deco-sites/persono/sections/Miscellaneous/CookieConsent.tsx": $$$$$$25,
    "deco-sites/persono/sections/Newsletter/Newsletter.tsx": $$$$$$26,
    "deco-sites/persono/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$27,
    "deco-sites/persono/sections/Product/ImageGallerySlider.tsx": $$$$$$28,
    "deco-sites/persono/sections/Product/NotFound.tsx": $$$$$$29,
    "deco-sites/persono/sections/Product/NotFoundChallenge.tsx": $$$$$$30,
    "deco-sites/persono/sections/Product/ProductBenefits.tsx": $$$$$$31,
    "deco-sites/persono/sections/Product/ProductInfo.tsx": $$$$$$32,
    "deco-sites/persono/sections/Product/ProductShelf.tsx": $$$$$$33,
    "deco-sites/persono/sections/Product/ProductShelfTabbed.tsx": $$$$$$34,
    "deco-sites/persono/sections/Product/SearchResult.tsx": $$$$$$35,
    "deco-sites/persono/sections/Product/Wishlist.tsx": $$$$$$36,
    "deco-sites/persono/sections/Social/InstagramPosts.tsx": $$$$$$37,
    "deco-sites/persono/sections/Social/WhatsApp.tsx": $$$$$$38,
    "deco-sites/persono/sections/Theme/Theme.tsx": $$$$$$39,
  },
  "apps": {
    "deco-sites/persono/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/persono/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/persono",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
